// This file is generated by scripts/generate-blog-registry.mjs.
// Do not edit it directly.

import type { ComponentType } from "react";
import type { MDXComponents } from "mdx/types";
import agenticSearchContent, { frontmatter as agenticSearchFrontmatter } from "./agentic-search.mdx";
import buildingReliableLlmApplicationsContent, { frontmatter as buildingReliableLlmApplicationsFrontmatter } from "./building-reliable-llm-applications.mdx";
import evalsAfterRagContent, { frontmatter as evalsAfterRagFrontmatter } from "./evals-after-rag.mdx";
import grepBeatsSqliteFtsContent, { frontmatter as grepBeatsSqliteFtsFrontmatter } from "./grep-beats-sqlite-fts.mdx";
import howDoesInstructorWorkContent, { frontmatter as howDoesInstructorWorkFrontmatter } from "./how-does-instructor-work.mdx";
import migratingToReactInkContent, { frontmatter as migratingToReactInkFrontmatter } from "./migrating-to-react-ink.mdx";
import reportErrorBarsContent, { frontmatter as reportErrorBarsFrontmatter } from "./report-error-bars.mdx";
import runningBetterExperimentsContent, { frontmatter as runningBetterExperimentsFrontmatter } from "./running-better-experiments.mdx";
import threeLessonsManusContent, { frontmatter as threeLessonsManusFrontmatter } from "./three-lessons-manus.mdx";
import writeStupidEvalsContent, { frontmatter as writeStupidEvalsFrontmatter } from "./write-stupid-evals.mdx";
import writingExtractionEvalsContent, { frontmatter as writingExtractionEvalsFrontmatter } from "./writing-extraction-evals.mdx";

export type BlogFrontmatter = {
  title?: string;
  date?: string;
  description?: string;
  author?: string;
  cover?: string;
};

export type BlogHeading = {
  text: string;
  id: string;
  level: number;
};

export type BlogPost = {
  slug: string;
  frontmatter: BlogFrontmatter;
  Content: ComponentType<{ components?: MDXComponents }>;
  headings: BlogHeading[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "agentic-search",
    frontmatter: agenticSearchFrontmatter,
    Content: agenticSearchContent,
    headings: [
        {
            "text": "Building Autocomplete",
            "id": "building-autocomplete",
            "level": 2
        },
        {
            "text": "Using Rigrep",
            "id": "using-rigrep",
            "level": 3
        },
        {
            "text": "Creating our UI",
            "id": "creating-our-ui",
            "level": 3
        },
        {
            "text": "Integrating with our Application",
            "id": "integrating-with-our-application",
            "level": 3
        },
        {
            "text": "Making Search Fast",
            "id": "making-search-fast",
            "level": 2
        },
        {
            "text": "Understanding the Tools",
            "id": "understanding-the-tools",
            "level": 3
        },
        {
            "text": "How They Work Together",
            "id": "how-they-work-together",
            "level": 3
        },
        {
            "text": "Implementing Grep and Glob",
            "id": "implementing-grep-and-glob",
            "level": 3
        },
        {
            "text": "Providing a Bash Shell",
            "id": "providing-a-bash-shell",
            "level": 2
        },
        {
            "text": "Adding Web Search with Exa",
            "id": "adding-web-search-with-exa",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "building-reliable-llm-applications",
    frontmatter: buildingReliableLlmApplicationsFrontmatter,
    Content: buildingReliableLlmApplicationsContent,
    headings: [
        {
            "text": "The New Development Paradigm",
            "id": "the-new-development-paradigm",
            "level": 2
        },
        {
            "text": "Structured Outputs",
            "id": "structured-outputs",
            "level": 2
        },
        {
            "text": "Why Raw JSON is not enough",
            "id": "why-raw-json-is-not-enough",
            "level": 3
        },
        {
            "text": "Beyond Simple Validation",
            "id": "beyond-simple-validation",
            "level": 3
        },
        {
            "text": "Prioritising Iteration Speed",
            "id": "prioritising-iteration-speed",
            "level": 2
        },
        {
            "text": "RAG Systems",
            "id": "rag-systems",
            "level": 3
        },
        {
            "text": "Text-to-SQL",
            "id": "text-to-sql",
            "level": 3
        },
        {
            "text": "Tool Selection",
            "id": "tool-selection",
            "level": 3
        },
        {
            "text": "Query Understanding",
            "id": "query-understanding",
            "level": 2
        },
        {
            "text": "The Value of Query Understanding",
            "id": "the-value-of-query-understanding",
            "level": 3
        },
        {
            "text": "How Kura Works",
            "id": "how-kura-works",
            "level": 3
        },
        {
            "text": "Validating with Synthetic Data",
            "id": "validating-with-synthetic-data",
            "level": 3
        },
        {
            "text": "Getting Started with Kura",
            "id": "getting-started-with-kura",
            "level": 3
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        },
        {
            "text": "Useful Links",
            "id": "useful-links",
            "level": 2
        }
    ],
  },
  {
    slug: "evals-after-rag",
    frontmatter: evalsAfterRagFrontmatter,
    Content: evalsAfterRagContent,
    headings: [
        {
            "text": "2025",
            "id": "2025",
            "level": 2
        },
        {
            "text": "2026",
            "id": "2026",
            "level": 2
        },
        {
            "text": "Steal this",
            "id": "steal-this",
            "level": 2
        },
        {
            "text": "What I am running next",
            "id": "what-i-am-running-next",
            "level": 2
        }
    ],
  },
  {
    slug: "grep-beats-sqlite-fts",
    frontmatter: grepBeatsSqliteFtsFrontmatter,
    Content: grepBeatsSqliteFtsContent,
    headings: [
        {
            "text": "Generating the Corpus",
            "id": "generating-the-corpus",
            "level": 2
        },
        {
            "text": "Creating the Environment",
            "id": "creating-the-environment",
            "level": 2
        },
        {
            "text": "Why did FTS lose?",
            "id": "why-did-fts-lose",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "how-does-instructor-work",
    frontmatter: howDoesInstructorWorkFrontmatter,
    Content: howDoesInstructorWorkContent,
    headings: [
        {
            "text": "Why should you care?",
            "id": "why-should-you-care",
            "level": 3
        },
        {
            "text": "High Level Flow",
            "id": "high-level-flow",
            "level": 2
        },
        {
            "text": "Parsing Responses and Handling Errors",
            "id": "parsing-responses-and-handling-errors",
            "level": 2
        },
        {
            "text": "The `from_openai` function",
            "id": "the-from_openai-function",
            "level": 3
        },
        {
            "text": "How does the Pydantic `response_model` keyword argument get used?",
            "id": "how-does-the-pydantic-response_model-keyword-argument-get-used",
            "level": 3
        },
        {
            "text": "How does the response from the LLM get validated?",
            "id": "how-does-the-response-from-the-llm-get-validated",
            "level": 3
        },
        {
            "text": "Why you probably shouldn't roll your own",
            "id": "why-you-probably-shouldnt-roll-your-own",
            "level": 2
        }
    ],
  },
  {
    slug: "migrating-to-react-ink",
    frontmatter: migratingToReactInkFrontmatter,
    Content: migratingToReactInkContent,
    headings: [
        {
            "text": "Starting Our Migration",
            "id": "starting-our-migration",
            "level": 2
        },
        {
            "text": "Initialising React-Ink",
            "id": "initialising-react-ink",
            "level": 3
        },
        {
            "text": "Integrating with Anthropic",
            "id": "integrating-with-anthropic",
            "level": 3
        },
        {
            "text": "Refactoring for Tool calling",
            "id": "refactoring-for-tool-calling",
            "level": 2
        },
        {
            "text": "Why Refactor our Application?",
            "id": "why-refactor-our-application",
            "level": 3
        },
        {
            "text": "Defining Our Tools",
            "id": "defining-our-tools",
            "level": 3
        },
        {
            "text": "Handling Content Blocks",
            "id": "handling-content-blocks",
            "level": 3
        },
        {
            "text": "Updating sendMessage",
            "id": "updating-sendmessage",
            "level": 3
        },
        {
            "text": "Adding Other Tools",
            "id": "adding-other-tools",
            "level": 2
        },
        {
            "text": "Updating `Message.tsx`",
            "id": "updating-messagetsx",
            "level": 3
        },
        {
            "text": "Adding more Tools",
            "id": "adding-more-tools",
            "level": 3
        }
    ],
  },
  {
    slug: "report-error-bars",
    frontmatter: reportErrorBarsFrontmatter,
    Content: reportErrorBarsContent,
    headings: [
        {
            "text": "Why RAG metrics matter",
            "id": "why-rag-metrics-matter",
            "level": 2
        },
        {
            "text": "Looking to the Future",
            "id": "looking-to-the-future",
            "level": 3
        },
        {
            "text": "Business-Driven Evaluation",
            "id": "business-driven-evaluation",
            "level": 3
        },
        {
            "text": "Comparing Three Retrieval Methods",
            "id": "comparing-three-retrieval-methods",
            "level": 2
        },
        {
            "text": "Measuring Uncertainty with Bootstrapping",
            "id": "measuring-uncertainty-with-bootstrapping",
            "level": 2
        },
        {
            "text": "Simplifying Bootstrap Analysis with `indomee`",
            "id": "simplifying-bootstrap-analysis-with-indomee",
            "level": 3
        },
        {
            "text": "Computing metrics at different k values",
            "id": "computing-metrics-at-different-k-values",
            "level": 3
        },
        {
            "text": "Working with Raw Bootstrap Data",
            "id": "working-with-raw-bootstrap-data",
            "level": 3
        },
        {
            "text": "Testing for Statistical Significance",
            "id": "testing-for-statistical-significance",
            "level": 2
        },
        {
            "text": "Simplifying t-tests with `indomee`",
            "id": "simplifying-t-tests-with-indomee",
            "level": 3
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "running-better-experiments",
    frontmatter: runningBetterExperimentsFrontmatter,
    Content: runningBetterExperimentsContent,
    headings: [
        {
            "text": "Knowing what to vary",
            "id": "knowing-what-to-vary",
            "level": 2
        },
        {
            "text": "Fast Feedback Loops",
            "id": "fast-feedback-loops",
            "level": 2
        },
        {
            "text": "Benchmark Evaluation",
            "id": "benchmark-evaluation",
            "level": 3
        },
        {
            "text": "Subjective Evaluation",
            "id": "subjective-evaluation",
            "level": 3
        },
        {
            "text": "Sensitivity Testing",
            "id": "sensitivity-testing",
            "level": 2
        },
        {
            "text": "Key Takeaways",
            "id": "key-takeaways",
            "level": 2
        }
    ],
  },
  {
    slug: "three-lessons-manus",
    frontmatter: threeLessonsManusFrontmatter,
    Content: threeLessonsManusContent,
    headings: [
        {
            "text": "What is Manus?",
            "id": "what-is-manus",
            "level": 2
        },
        {
            "text": "What I've Learnt",
            "id": "what-ive-learnt",
            "level": 2
        },
        {
            "text": "Join us!",
            "id": "join-us",
            "level": 2
        }
    ],
  },
  {
    slug: "write-stupid-evals",
    frontmatter: writeStupidEvalsFrontmatter,
    Content: writeStupidEvalsContent,
    headings: [
        {
            "text": "Write Stupid Evals",
            "id": "write-stupid-evals",
            "level": 2
        },
        {
            "text": "The Case for Simple Evaluations",
            "id": "the-case-for-simple-evaluations",
            "level": 3
        },
        {
            "text": "1. Discord's Casual Chat Detection",
            "id": "1-discords-casual-chat-detection",
            "level": 3
        },
        {
            "text": "2. Retrieval Quality for SQL Queries",
            "id": "2-retrieval-quality-for-sql-queries",
            "level": 3
        },
        {
            "text": "3. Testing Tool Selection for Agents",
            "id": "3-testing-tool-selection-for-agents",
            "level": 3
        },
        {
            "text": "Building the Evaluation Muscle",
            "id": "building-the-evaluation-muscle",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "writing-extraction-evals",
    frontmatter: writingExtractionEvalsFrontmatter,
    Content: writingExtractionEvalsContent,
    headings: [
        {
            "text": "The Initial Challenge",
            "id": "the-initial-challenge",
            "level": 2
        },
        {
            "text": "Moving to Binary Metrics with Synthetic Data",
            "id": "moving-to-binary-metrics-with-synthetic-data",
            "level": 2
        },
        {
            "text": "Starting with Synthetic Data",
            "id": "starting-with-synthetic-data",
            "level": 3
        },
        {
            "text": "Using Citations",
            "id": "using-citations",
            "level": 3
        },
        {
            "text": "Why Binary Metrics work",
            "id": "why-binary-metrics-work",
            "level": 3
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  }
];

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
