// This file is generated by scripts/generate-blog-registry.mjs.
// Do not edit it directly.

import type { ComponentType } from "react";
import type { MDXComponents } from "mdx/types";
import agenticSearchContent, { frontmatter as agenticSearchFrontmatter } from "./agentic-search.mdx";
import grepBeatsSqliteFtsContent, { frontmatter as grepBeatsSqliteFtsFrontmatter } from "./grep-beats-sqlite-fts.mdx";
import howDoesInstructorWorkContent, { frontmatter as howDoesInstructorWorkFrontmatter } from "./how-does-instructor-work.mdx";
import mcpsAreReallyLlmMicroservicesContent, { frontmatter as mcpsAreReallyLlmMicroservicesFrontmatter } from "./mcps-are-really-llm-microservices.mdx";
import migratingToReactInkContent, { frontmatter as migratingToReactInkFrontmatter } from "./migrating-to-react-ink.mdx";
import threeLessonsManusContent, { frontmatter as threeLessonsManusFrontmatter } from "./three-lessons-manus.mdx";
import writeStupidEvalsContent, { frontmatter as writeStupidEvalsFrontmatter } from "./write-stupid-evals.mdx";

export type BlogFrontmatter = {
  title?: string;
  date?: string;
  description?: string;
  author?: string;
  cover?: string;
};

export type BlogHeading = {
  text: string;
  id: string;
  level: number;
};

export type BlogPost = {
  slug: string;
  frontmatter: BlogFrontmatter;
  Content: ComponentType<{ components?: MDXComponents }>;
  headings: BlogHeading[];
};

export const blogPosts: BlogPost[] = [
  {
    slug: "agentic-search",
    frontmatter: agenticSearchFrontmatter,
    Content: agenticSearchContent,
    headings: [
        {
            "text": "Building Autocomplete",
            "id": "building-autocomplete",
            "level": 2
        },
        {
            "text": "Using Rigrep",
            "id": "using-rigrep",
            "level": 3
        },
        {
            "text": "Creating our UI",
            "id": "creating-our-ui",
            "level": 3
        },
        {
            "text": "Integrating with our Application",
            "id": "integrating-with-our-application",
            "level": 3
        },
        {
            "text": "Making Search Fast",
            "id": "making-search-fast",
            "level": 2
        },
        {
            "text": "Understanding the Tools",
            "id": "understanding-the-tools",
            "level": 3
        },
        {
            "text": "How They Work Together",
            "id": "how-they-work-together",
            "level": 3
        },
        {
            "text": "Implementing Grep and Glob",
            "id": "implementing-grep-and-glob",
            "level": 3
        },
        {
            "text": "Providing a Bash Shell",
            "id": "providing-a-bash-shell",
            "level": 2
        },
        {
            "text": "Adding Web Search with Exa",
            "id": "adding-web-search-with-exa",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "grep-beats-sqlite-fts",
    frontmatter: grepBeatsSqliteFtsFrontmatter,
    Content: grepBeatsSqliteFtsContent,
    headings: [
        {
            "text": "Generating the Corpus",
            "id": "generating-the-corpus",
            "level": 2
        },
        {
            "text": "Creating the Environment",
            "id": "creating-the-environment",
            "level": 2
        },
        {
            "text": "Why did FTS lose?",
            "id": "why-did-fts-lose",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "how-does-instructor-work",
    frontmatter: howDoesInstructorWorkFrontmatter,
    Content: howDoesInstructorWorkContent,
    headings: [
        {
            "text": "Why should you care?",
            "id": "why-should-you-care",
            "level": 3
        },
        {
            "text": "High Level Flow",
            "id": "high-level-flow",
            "level": 2
        },
        {
            "text": "Parsing Responses and Handling Errors",
            "id": "parsing-responses-and-handling-errors",
            "level": 2
        },
        {
            "text": "The `from_openai` function",
            "id": "the-from_openai-function",
            "level": 3
        },
        {
            "text": "How does the Pydantic `response_model` keyword argument get used?",
            "id": "how-does-the-pydantic-response_model-keyword-argument-get-used",
            "level": 3
        },
        {
            "text": "How does the response from the LLM get validated?",
            "id": "how-does-the-response-from-the-llm-get-validated",
            "level": 3
        },
        {
            "text": "Why you probably shouldn't roll your own",
            "id": "why-you-probably-shouldnt-roll-your-own",
            "level": 2
        }
    ],
  },
  {
    slug: "mcps-are-really-llm-microservices",
    frontmatter: mcpsAreReallyLlmMicroservicesFrontmatter,
    Content: mcpsAreReallyLlmMicroservicesContent,
    headings: [
        {
            "text": "The Current State of Tool Integration",
            "id": "the-current-state-of-tool-integration",
            "level": 2
        },
        {
            "text": "Understanding MCPs: More Than Just Another API Spec",
            "id": "understanding-mcps-more-than-just-another-api-spec",
            "level": 2
        },
        {
            "text": "The Infrastructure Gap",
            "id": "the-infrastructure-gap",
            "level": 2
        },
        {
            "text": "Looking Forward: Adaptive AI Microservices",
            "id": "looking-forward-adaptive-ai-microservices",
            "level": 2
        },
        {
            "text": "Monetized Specialisation",
            "id": "monetized-specialisation",
            "level": 3
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  },
  {
    slug: "migrating-to-react-ink",
    frontmatter: migratingToReactInkFrontmatter,
    Content: migratingToReactInkContent,
    headings: [
        {
            "text": "Starting Our Migration",
            "id": "starting-our-migration",
            "level": 2
        },
        {
            "text": "Initialising React-Ink",
            "id": "initialising-react-ink",
            "level": 3
        },
        {
            "text": "Integrating with Anthropic",
            "id": "integrating-with-anthropic",
            "level": 3
        },
        {
            "text": "Refactoring for Tool calling",
            "id": "refactoring-for-tool-calling",
            "level": 2
        },
        {
            "text": "Why Refactor our Application?",
            "id": "why-refactor-our-application",
            "level": 3
        },
        {
            "text": "Defining Our Tools",
            "id": "defining-our-tools",
            "level": 3
        },
        {
            "text": "Handling Content Blocks",
            "id": "handling-content-blocks",
            "level": 3
        },
        {
            "text": "Updating sendMessage",
            "id": "updating-sendmessage",
            "level": 3
        },
        {
            "text": "Adding Other Tools",
            "id": "adding-other-tools",
            "level": 2
        },
        {
            "text": "Updating `Message.tsx`",
            "id": "updating-messagetsx",
            "level": 3
        },
        {
            "text": "Adding more Tools",
            "id": "adding-more-tools",
            "level": 3
        }
    ],
  },
  {
    slug: "three-lessons-manus",
    frontmatter: threeLessonsManusFrontmatter,
    Content: threeLessonsManusContent,
    headings: [
        {
            "text": "What is Manus?",
            "id": "what-is-manus",
            "level": 2
        },
        {
            "text": "What I've Learnt",
            "id": "what-ive-learnt",
            "level": 2
        },
        {
            "text": "Join us!",
            "id": "join-us",
            "level": 2
        }
    ],
  },
  {
    slug: "write-stupid-evals",
    frontmatter: writeStupidEvalsFrontmatter,
    Content: writeStupidEvalsContent,
    headings: [
        {
            "text": "Write Stupid Evals",
            "id": "write-stupid-evals",
            "level": 2
        },
        {
            "text": "The Case for Simple Evaluations",
            "id": "the-case-for-simple-evaluations",
            "level": 3
        },
        {
            "text": "1. Discord's Casual Chat Detection",
            "id": "1-discords-casual-chat-detection",
            "level": 3
        },
        {
            "text": "2. Retrieval Quality for SQL Queries",
            "id": "2-retrieval-quality-for-sql-queries",
            "level": 3
        },
        {
            "text": "3. Testing Tool Selection for Agents",
            "id": "3-testing-tool-selection-for-agents",
            "level": 3
        },
        {
            "text": "Building the Evaluation Muscle",
            "id": "building-the-evaluation-muscle",
            "level": 2
        },
        {
            "text": "Conclusion",
            "id": "conclusion",
            "level": 2
        }
    ],
  }
];

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug);
}
